export let peopleArray = [
  "Stian",
  "Ghouthami",
  "Tord",
  "Inna",
  "Erik",
  "Katerina",
  "Emilie",
  "Adrian",
  "Henry",
  "Camilla",
  "Kristian",
  "Andreas",
  "Ilakia",
  "Espen",
  "Emir",
  "John",
  "Migal",
  "André K",
  "Adrian K",
  "Kristina",
  "Stein",
  "Sebastian",
  "Jesper",
  "Eirik",
  "Ingmar",
  "Stein Inge",
  "Joakim",
  "Trond-Morten",
  "Marius",
  "Robert",
];

export const Elements = {
  peopleCheckList: document.querySelector("#People-checklist"),
  peopleRandom: document.querySelector("#Pant-randomizer"),
  firstPerson: document.querySelector("#first-Person"),
  secondPerson: document.querySelector("#second-Person"),
  submitPeople: document.querySelector("#Submit-People"),
};
